# Generated by Django 4.0.1 on 2022-02-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=222)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
