# Generated by Django 4.0.1 on 2022-02-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monacc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
